[window]
height = 1080
width = 1920
title = "Rule30 Simulation"
isFullscreen = true
targetFPS = 60

[simulation]
simDepth = 200

[render]
primaryColor = [ 3, 90, 252 ]
secondaryColor = [ 0, 0, 0]
bgColor = [0, 0, 0]